language: cpp
dist: xenial
sudo: required
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install qtbase5-dev qttools5-dev-tools
  - sudo apt-get install libsdl-mixer1.2-dev
script:
  - cmake -DCMAKE_CXX_FLAGS="-Wall -Wextra" .
  - make
  - sudo make install
