#############################################################################
# Makefile for building: qnetwalk
# Generated by qmake (2.01a) (Qt 4.6.3) on: ?? ???. 10 15:03:31 2013
# Project:  qnetwalk.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile qnetwalk.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lSDL_mixer -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = cell.cpp \
		main.cpp \
		mainwindow.cpp \
		sound.cpp moc_cell.cpp \
		moc_mainwindow.cpp \
		qrc_qnetwalk.cpp
OBJECTS       = cell.o \
		main.o \
		mainwindow.o \
		sound.o \
		moc_cell.o \
		moc_mainwindow.o \
		qrc_qnetwalk.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		qnetwalk.pro
QMAKE_TARGET  = qnetwalk
DESTDIR       = 
TARGET        = qnetwalk

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qnetwalk.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile qnetwalk.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile qnetwalk.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qnetwalk1.0.0 || $(MKDIR) .tmp/qnetwalk1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qnetwalk1.0.0/ && $(COPY_FILE) --parents cell.h mainwindow.h sound.h .tmp/qnetwalk1.0.0/ && $(COPY_FILE) --parents qnetwalk.qrc .tmp/qnetwalk1.0.0/ && $(COPY_FILE) --parents cell.cpp main.cpp mainwindow.cpp sound.cpp .tmp/qnetwalk1.0.0/ && $(COPY_FILE) --parents translations/qnetwalk_de.ts translations/qnetwalk_es.ts translations/qnetwalk_fr.ts translations/qnetwalk_it.ts translations/qnetwalk_nl.ts translations/qnetwalk_pl.ts translations/qnetwalk_pt_BR.ts translations/qnetwalk_ru.ts translations/qnetwalk_tr.ts translations/qnetwalk_ua.ts translations/qnetwalk_zh_CN.ts .tmp/qnetwalk1.0.0/ && (cd `dirname .tmp/qnetwalk1.0.0` && $(TAR) qnetwalk1.0.0.tar qnetwalk1.0.0 && $(COMPRESS) qnetwalk1.0.0.tar) && $(MOVE) `dirname .tmp/qnetwalk1.0.0`/qnetwalk1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qnetwalk1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_cell.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_cell.cpp moc_mainwindow.cpp
moc_cell.cpp: cell.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) cell.h -o moc_cell.cpp

moc_mainwindow.cpp: mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all: qrc_qnetwalk.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qnetwalk.cpp
qrc_qnetwalk.cpp: qnetwalk.qrc \
		pics/cable0111.png \
		pics/cable1101.png \
		pics/homepage.png \
		pics/qnetwalk.png \
		pics/server.png \
		pics/shadow.png \
		pics/computer1.png \
		pics/cable0010.png \
		pics/cable1000.png \
		pics/locked.png \
		pics/newgame.png \
		pics/cable0001.png \
		pics/cable1010.png \
		pics/background.png \
		pics/highscores.png \
		pics/computer2.png \
		pics/focus.png \
		pics/cable0100.png \
		pics/cable0011.png \
		pics/quit.png \
		pics/cable1001.png \
		pics/cable0110.png \
		pics/cable1100.png \
		pics/cable1011.png \
		pics/cable0101.png \
		pics/cable1110.png
	/usr/bin/rcc -name qnetwalk qnetwalk.qrc -o qrc_qnetwalk.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

cell.o: cell.cpp cell.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cell.o cell.cpp

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp cell.h \
		mainwindow.h \
		sound.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

sound.o: sound.cpp sound.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sound.o sound.cpp

moc_cell.o: moc_cell.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cell.o moc_cell.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

qrc_qnetwalk.o: qrc_qnetwalk.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qnetwalk.o qrc_qnetwalk.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/games/ || $(MKDIR) $(INSTALL_ROOT)/usr/games/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/games/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/usr/games/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/games/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/games/ 


install_man: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/man/man6/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/man/man6/ 
	-$(INSTALL_FILE) /root/qnetwalk/qnetwalk.6 $(INSTALL_ROOT)/usr/share/man/man6/


uninstall_man:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/man/man6/qnetwalk.6
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/man/man6/ 


install_tr: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/qnetwalk/translations/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/qnetwalk/translations/ 
	-$(INSTALL_FILE) /root/qnetwalk/translations/qnetwalk_de.qm $(INSTALL_ROOT)/usr/share/qnetwalk/translations/
	-$(INSTALL_FILE) /root/qnetwalk/translations/qnetwalk_es.qm $(INSTALL_ROOT)/usr/share/qnetwalk/translations/
	-$(INSTALL_FILE) /root/qnetwalk/translations/qnetwalk_fr.qm $(INSTALL_ROOT)/usr/share/qnetwalk/translations/
	-$(INSTALL_FILE) /root/qnetwalk/translations/qnetwalk_it.qm $(INSTALL_ROOT)/usr/share/qnetwalk/translations/
	-$(INSTALL_FILE) /root/qnetwalk/translations/qnetwalk_nl.qm $(INSTALL_ROOT)/usr/share/qnetwalk/translations/
	-$(INSTALL_FILE) /root/qnetwalk/translations/qnetwalk_pl.qm $(INSTALL_ROOT)/usr/share/qnetwalk/translations/
	-$(INSTALL_FILE) /root/qnetwalk/translations/qnetwalk_pt_BR.qm $(INSTALL_ROOT)/usr/share/qnetwalk/translations/
	-$(INSTALL_FILE) /root/qnetwalk/translations/qnetwalk_ru.qm $(INSTALL_ROOT)/usr/share/qnetwalk/translations/
	-$(INSTALL_FILE) /root/qnetwalk/translations/qnetwalk_tr.qm $(INSTALL_ROOT)/usr/share/qnetwalk/translations/
	-$(INSTALL_FILE) /root/qnetwalk/translations/qnetwalk_ua.qm $(INSTALL_ROOT)/usr/share/qnetwalk/translations/
	-$(INSTALL_FILE) /root/qnetwalk/translations/qnetwalk_zh_CN.qm $(INSTALL_ROOT)/usr/share/qnetwalk/translations/


uninstall_tr:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qnetwalk/translations/qnetwalk_de.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qnetwalk/translations/qnetwalk_es.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qnetwalk/translations/qnetwalk_fr.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qnetwalk/translations/qnetwalk_it.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qnetwalk/translations/qnetwalk_nl.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qnetwalk/translations/qnetwalk_pl.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qnetwalk/translations/qnetwalk_pt_BR.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qnetwalk/translations/qnetwalk_ru.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qnetwalk/translations/qnetwalk_tr.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qnetwalk/translations/qnetwalk_ua.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qnetwalk/translations/qnetwalk_zh_CN.qm
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/qnetwalk/translations/ 


install_sounds: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/qnetwalk/sounds/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/qnetwalk/sounds/ 
	-$(INSTALL_FILE) /root/qnetwalk/sounds/click.wav $(INSTALL_ROOT)/usr/share/qnetwalk/sounds/
	-$(INSTALL_FILE) /root/qnetwalk/sounds/connect.wav $(INSTALL_ROOT)/usr/share/qnetwalk/sounds/
	-$(INSTALL_FILE) /root/qnetwalk/sounds/start.wav $(INSTALL_ROOT)/usr/share/qnetwalk/sounds/
	-$(INSTALL_FILE) /root/qnetwalk/sounds/turn.wav $(INSTALL_ROOT)/usr/share/qnetwalk/sounds/
	-$(INSTALL_FILE) /root/qnetwalk/sounds/win.wav $(INSTALL_ROOT)/usr/share/qnetwalk/sounds/


uninstall_sounds:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qnetwalk/sounds/click.wav 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qnetwalk/sounds/connect.wav 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qnetwalk/sounds/start.wav 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qnetwalk/sounds/turn.wav 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qnetwalk/sounds/win.wav
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/qnetwalk/sounds/ 


install_link: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/applications/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/applications/ 
	-$(INSTALL_FILE) /root/qnetwalk/menu/qnetwalk.desktop $(INSTALL_ROOT)/usr/share/applications/


uninstall_link:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/qnetwalk.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install_icon: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/pixmaps/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/pixmaps/ 
	-$(INSTALL_FILE) /root/qnetwalk/menu/qnetwalk.xpm $(INSTALL_ROOT)/usr/share/pixmaps/


uninstall_icon:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/pixmaps/qnetwalk.xpm
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/pixmaps/ 


install_menu: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/menu/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/menu/ 
	-$(INSTALL_FILE) /root/qnetwalk/menu/qnetwalk $(INSTALL_ROOT)/usr/share/menu/


uninstall_menu:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/menu/qnetwalk
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/menu/ 


install:  install_target install_man install_tr install_sounds install_link install_icon install_menu  FORCE

uninstall: uninstall_target uninstall_man uninstall_tr uninstall_sounds uninstall_link uninstall_icon uninstall_menu   FORCE

FORCE:

