name: CI
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { cc: gcc, cxx: g++ }
          - { cc: clang, cxx: clang++ }
    steps:
      - uses: actions/checkout@v3
      - name: Set up environment
        run: |
          echo 'CC=${{ matrix.cc }}' >> $GITHUB_ENV
          echo 'CXX=${{ matrix.cxx }}' >> $GITHUB_ENV
          echo 'CFLAGS=-Werror -Wall -Wextra -pedantic' >> $GITHUB_ENV
          echo 'CXXFLAGS=-Werror -Wall -Wextra -pedantic' >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install qtbase5-dev qttools5-dev libsdl2-mixer-dev appstream-util
      - name: Validate appstream file
        run: appstream-util validate-relax --nonet menu/*.metainfo.xml
      - name: Configure
        run: cmake . -DCMAKE_VERBOSE_MAKEFILE=yes -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug
      - name: Build
        run: cmake --build .
      - name: Install
        run: sudo cmake --install .
